# Generated by Django 5.2.3 on 2025-06-15 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('freelancer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('habilidades_requeridas', models.JSONField()),
                ('estado', models.CharField(blank=True, help_text='Ex: SP, RJ', max_length=2, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(blank=True, help_text='Formato: 12345-678', max_length=9, null=True)),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'PENDENTE'), (2, 'EM_ANDAMENTO'), (3, 'CONCLUÍDO')])),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='freelancer.perfil')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
