# Generated by Django 5.2.3 on 2025-06-10 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('freelancer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('imagens', models.ImageField(blank=True, null=True, upload_to='portfolio/imagens')),
                ('links', models.URLField(blank=True, null=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='freelancer.perfil')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
