# Generated by Django 5.2.3 on 2025-06-15 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.SmallIntegerField(choices=[(1, 'FREELANCER'), (2, 'CLIENTE')])),
                ('nome', models.CharField(max_length=100)),
                ('estado', models.CharField(blank=True, help_text='Ex: SP, RJ', max_length=2, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(blank=True, help_text='Formato: 12345-678', max_length=9, null=True)),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('telefone', models.CharField(blank=True, help_text='Ex: (11) 91234-5678', max_length=15, null=True)),
                ('email_contato', models.EmailField(blank=True, max_length=254, null=True)),
                ('habilidades', models.JSONField()),
                ('bio', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='freelancer/fotos')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
