# Generated by Django 5.2.3 on 2025-06-10 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('freelancer', '0001_initial'),
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tempo_estimado', models.CharField(max_length=50)),
                ('mensagem', models.TextField()),
                ('status', models.SmallIntegerField(choices=[(1, 'PENDENTE'), (2, 'ACEITA'), (3, 'REJEITADA')])),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='freelancer.perfil')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='projeto.projeto')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
